services:

    vite.entrypoints_lookup:
        class: Pentatrion\ViteBundle\Asset\EntrypointsLookup
        arguments:
            - "%kernel.project_dir%%pentatrion_vite.public_directory%"
            - "%pentatrion_vite.default_build%"
            - "%pentatrion_vite.builds%"
            - "%pentatrion_vite.throw_on_missing_entry%"

    Pentatrion\ViteBundle\Asset\EntrypointsLookup:
        alias: "vite.entrypoints_lookup"

    vite.entrypoint_renderer:
        class: Pentatrion\ViteBundle\Asset\EntrypointRenderer
        arguments:
            - "@vite.entrypoints_lookup"
            - "@vite.tag_renderer"
            - "%pentatrion_vite.absolute_url%"
            - "@?router"

    Pentatrion\ViteBundle\Asset\EntrypointRenderer:
        alias: "vite.entrypoint_renderer"

    vite.tag_renderer:
        class: Pentatrion\ViteBundle\Asset\TagRenderer
        arguments:
            - default # Default default_build
            - []      # Default builds
            - "@?event_dispatcher"

    

    vite.twig_entry_files_extension:
        class: Pentatrion\ViteBundle\Twig\EntryFilesTwigExtension
        tags: ["twig.extension"]
        arguments:
            - "@vite.entrypoint_renderer"

    Pentatrion\ViteBundle\Controller\ViteController:
        tags: ["controller.service_arguments"]
        arguments:
            - "%pentatrion_vite.default_build%"
            - "%pentatrion_vite.builds%"
            - "@http_client"
            - "@vite.entrypoints_lookup"
            - "%pentatrion_vite.proxy_origin%"

    Pentatrion\ViteBundle\Asset\ViteAssetVersionStrategy:
        arguments:
            - "%kernel.project_dir%%pentatrion_vite.public_directory%"
            - "%pentatrion_vite.builds%"
            - "%pentatrion_vite.default_build%"
            - "%pentatrion_vite.absolute_url%"
            - "@?router"
            - true
